plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'


repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.4'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.4'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testImplementation group: 'org.mockito', name: 'mockito-junit-jupiter', version: '5.14.2'
}


test {
    useJUnitPlatform()
}